---
# Documentation: https://metallb.org/configuration/#announce-the-service-ips
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - 192.168.0.100-192.168.0.200
