---
# Documentation: https://metallb.org/configuration/#announce-the-service-ips
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
