repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/stackrox/kube-linter
    rev: 0.5.0
    hooks:
      - id: kube-linter-system
        args:
          - lint
        files: apps\/(.+)\/(.+)\.yml
        exclude: apps\/(.+)\/overlays/(.+)\.yml
ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
