---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.6.2
  nodeSets:
    - name: master
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.security.enabled: false
      podTemplate:
        spec:
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install --batch \
                  http://www.landisk.lab/elasticsearch/plugins/analysis-kuromoji/analysis-kuromoji-8.6.2.zip;
                  bin/elasticsearch-plugin install --batch \
                  http://www.landisk.lab/elasticsearch/plugins/analysis-nori/analysis-nori-8.6.2.zip;
                  exit 0;
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: nfs
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 10Gi
  http:
    tls:
      selfSignedCertificate:
        disabled: true
