---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dns
  - metallb.yml
  - namespace.yml
  - nginx-ingress-service.yml
  # Elasticsearch
  - https://download.elastic.co/downloads/eck/2.4.0/crds.yaml
  - https://download.elastic.co/downloads/eck/2.4.0/operator.yaml
