---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress
  annotations:
    kube-score/ignore: |
      service-targets-pod
spec:
  selector:
    name: nginx-ingress-microk8s
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.0.101
