---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawa-trpl-upload
spec:
  storageClassName: nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
