---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - pdb.yml
  - service.yml

configMapGenerator:
  - name: coredns-config
    files:
      - Corefile
