---
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  selector:
    app: coredns
  ports:
    - port: 53
      protocol: UDP
      name: dns
  type: LoadBalancer
  loadBalancerIP: 192.168.0.100
